version: "3.8"

services:
  catalogdb: 
    image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

volumes:
  postgres_catalog:
