version: "3.8"

services:
  catalogdb:          
    container_name: catalogdb
    environment:
      - POSTGRES_USER=cataloguser
      - POSTGRES_PASSWORD=catalogpassword
      - POSTGRES_DB=catalogdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    networks:
        - pg-network
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__CatalogDb=Host=catalogdb;Database=catalogdb;User Id=cataloguser;Password=catalogpassword;Persist Security Info=True;Trust Server Certificate=True
    depends_on: 
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
networks:
    pg-network:
        external: true
